# Generated by Django 6.1 on 2026-08-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('normalized_query', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('state', models.CharField(max_length=2)),
                ('country_code', models.CharField(max_length=3)),
                ('provider', models.CharField(default='openrouteservice', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePlanCache',
            fields=[
                ('cache_key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('data_version', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('opis_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.CharField(blank=True, max_length=30)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=11)),
                ('geocode_quality', models.CharField(choices=[('exact', 'Exact address'), ('city_centroid', 'City centroid')], max_length=20)),
                ('data_version', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'ordering': ('opis_id',),
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='planner_fue_latitud_a0ae5a_idx')],
            },
        ),
    ]
